# **Barcelona GP 2026**

In [2]:
#Imports
import fastf1
import pandas as pd
print("Imported!")

Imported!

In [7]:
#Caching
fastf1.Cache.enable_cache("../../cache")
print("Caching Enabled!")

Caching Enabled!

In [ ]:
#Define Session
session = fastf1.get_session(
    2025,
    "Spanish Grand Prix",
    "Q"
)
print("Session Defined")

Session Defined

In [11]:
#Load Session
session.load()
print("Session Loaded")

core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '63', '44', '12', '16', '10', '6', '14', '23', '5', '30', '18', '87', '27', '31', '55', '43', '22']

Session Loaded

In [12]:
#Grand Prix Overview
session

2025 Season Round 9: Spanish Grand Prix - Qualifying

In [13]:
#Results of Spain GP 2025
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,1.0,,NaN,0 days 00:01:12.551000,0 days 00:01:11.998000,0 days 00:01:11.546000,NaT,,NaN,NaN
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,2.0,,NaN,0 days 00:01:12.799000,0 days 00:01:12.056000,0 days 00:01:11.755000,NaT,,NaN,NaN
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,3.0,,NaN,0 days 00:01:12.798000,0 days 00:01:12.358000,0 days 00:01:11.848000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,4.0,,NaN,0 days 00:01:12.806000,0 days 00:01:12.407000,0 days 00:01:11.848000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,,NaN,0 days 00:01:13.058000,0 days 00:01:12.447000,0 days 00:01:12.045000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,6.0,,NaN,0 days 00:01:12.815000,0 days 00:01:12.585000,0 days 00:01:12.111000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,7.0,,NaN,0 days 00:01:13.014000,0 days 00:01:12.495000,0 days 00:01:12.131000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,8.0,,NaN,0 days 00:01:13.081000,0 days 00:01:12.611000,0 days 00:01:12.199000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6C98FF,rb,Isack,Hadjar,Isack Hadjar,...,9.0,,NaN,0 days 00:01:13.139000,0 days 00:01:12.461000,0 days 00:01:12.252000,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,10.0,,NaN,0 days 00:01:13.102000,0 days 00:01:12.523000,0 days 00:01:12.284000,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,11.0,,NaN,0 days 00:01:13.044000,0 days 00:01:12.641000,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,01C00E,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,12.0,,NaN,0 days 00:01:13.045000,0 days 00:01:12.756000,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,13.0,,NaN,0 days 00:01:13.039000,0 days 00:01:12.763000,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,14.0,,NaN,0 days 00:01:13.038000,0 days 00:01:13.058000,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,15.0,,NaN,0 days 00:01:13.074000,0 days 00:01:13.315000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,01C00E,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,16.0,,NaN,0 days 00:01:13.190000,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,17.0,,NaN,0 days 00:01:13.201000,NaT,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,18.0,,NaN,0 days 00:01:13.203000,NaT,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,19.0,,NaN,0 days 00:01:13.334000,NaT,NaT,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Red Bull Racing,4781D7,red_bull,Yuki,Tsunoda,Yuki Tsunoda,...,20.0,,NaN,0 days 00:01:13.385000,NaT,NaT,NaT,,NaN,NaN

In [ ]:
#GP Quali Results with Filters
session.results[["Abbreviation","TeamName","Position"]]

   Abbreviation         TeamName  Position
81          PIA          McLaren       1.0
4           NOR          McLaren       2.0
1           VER  Red Bull Racing       3.0
63          RUS         Mercedes       4.0
44          HAM          Ferrari       5.0
12          ANT         Mercedes       6.0
16          LEC          Ferrari       7.0
10          GAS           Alpine       8.0
6           HAD     Racing Bulls       9.0
14          ALO     Aston Martin      10.0
23          ALB         Williams      11.0
5           BOR      Kick Sauber      12.0
30          LAW     Racing Bulls      13.0
18          STR     Aston Martin      14.0
87          BEA     Haas F1 Team      15.0
27          HUL      Kick Sauber      16.0
31          OCO     Haas F1 Team      17.0
55          SAI         Williams      18.0
43          COL           Alpine      19.0
22          TSU  Red Bull Racing      20.0

## Race Analysis

In [17]:
import sys

sys.path.append("../..")

import Sliplib.slipload as sl

In [18]:
#Load Race session
race = sl.load_gp(2025,"Spanish Grand Prix","Race")

In [21]:
race.load()

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

In [24]:
race.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:32:57.375000,Finished,25.0,66.0
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.471000,Finished,18.0,66.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3.0,3,7.0,NaT,NaT,NaT,0 days 00:00:10.455000,Finished,15.0,66.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:11.359000,Finished,12.0,66.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,01C00E,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,5.0,5,15.0,NaT,NaT,NaT,0 days 00:00:13.648000,Finished,10.0,66.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,6.0,6,5.0,NaT,NaT,NaT,0 days 00:00:15.508000,Finished,8.0,66.0
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6C98FF,rb,Isack,Hadjar,Isack Hadjar,...,7.0,7,9.0,NaT,NaT,NaT,0 days 00:00:16.022000,Finished,6.0,66.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:17.882000,Finished,4.0,66.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,9.0,9,10.0,NaT,NaT,NaT,0 days 00:00:21.564000,Finished,2.0,66.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,10.0,10,3.0,NaT,NaT,NaT,0 days 00:00:21.826000,Finished,1.0,66.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,11.0,11,13.0,NaT,NaT,NaT,0 days 00:00:25.532000,Finished,0.0,66.0
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,01C00E,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,12.0,12,12.0,NaT,NaT,NaT,0 days 00:00:25.996000,Finished,0.0,66.0
22,22,Y TSUNODA,TSU,tsunoda,Red Bull Racing,4781D7,red_bull,Yuki,Tsunoda,Yuki Tsunoda,...,13.0,13,19.0,NaT,NaT,NaT,0 days 00:00:28.822000,Finished,0.0,66.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,14.0,14,17.0,NaT,NaT,NaT,0 days 00:00:29.309000,Finished,0.0,66.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,15.0,15,18.0,NaT,NaT,NaT,0 days 00:00:31.381000,Finished,0.0,66.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,16.0,16,16.0,NaT,NaT,NaT,0 days 00:00:32.197000,Finished,0.0,66.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,17.0,17,14.0,NaT,NaT,NaT,0 days 00:00:37.065000,Finished,0.0,66.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,18.0,R,6.0,NaT,NaT,NaT,NaT,Retired,0.0,53.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,19.0,R,11.0,NaT,NaT,NaT,NaT,Retired,0.0,27.0

In [23]:
#Fetch results
race.results[["Abbreviation","TeamName","ClassifiedPosition"]]

   Abbreviation         TeamName ClassifiedPosition
81          PIA          McLaren                  1
4           NOR          McLaren                  2
16          LEC          Ferrari                  3
63          RUS         Mercedes                  4
27          HUL      Kick Sauber                  5
44          HAM          Ferrari                  6
6           HAD     Racing Bulls                  7
10          GAS           Alpine                  8
14          ALO     Aston Martin                  9
1           VER  Red Bull Racing                 10
30          LAW     Racing Bulls                 11
5           BOR      Kick Sauber                 12
22          TSU  Red Bull Racing                 13
55          SAI         Williams                 14
43          COL           Alpine                 15
31          OCO     Haas F1 Team                 16
87          BEA     Haas F1 Team                 17
12          ANT         Mercedes                  R
23          ALB         Williams                  R

In [25]:
race.results[["Abbreviation","Position","Status"]]

   Abbreviation  Position    Status
81          PIA       1.0  Finished
4           NOR       2.0  Finished
16          LEC       3.0  Finished
63          RUS       4.0  Finished
27          HUL       5.0  Finished
44          HAM       6.0  Finished
6           HAD       7.0  Finished
10          GAS       8.0  Finished
14          ALO       9.0  Finished
1           VER      10.0  Finished
30          LAW      11.0  Finished
5           BOR      12.0  Finished
22          TSU      13.0  Finished
55          SAI      14.0  Finished
43          COL      15.0  Finished
31          OCO      16.0  Finished
87          BEA      17.0  Finished
12          ANT      18.0   Retired
23          ALB      19.0   Retired