# Telemetry Analysis

In [1]:
#Imports
import sys
sys.path.append("../..")
import Sliplib.slipload as sl
import Sliplib.selection as slipsel
import Sliplib.plotting as slpolt

In [3]:
# Select GP and Load Session
session = sl.load_gp(2025,"Spanish Grand Prix","Race")
session.load()

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

In [5]:
# Extract Lap Data
laps = session.laps
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:00:37.344000,VER,1,0 days 00:01:23.696000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.318000,...,False,Red Bull Racing,0 days 00:59:13.393000,2025-06-01 13:03:17.591,1,2.0,False,,False,False
1,0 days 01:01:57.427000,VER,1,0 days 00:01:20.083000,2.0,1.0,NaT,NaT,0 days 00:00:24.125000,0 days 00:00:32.278000,...,False,Red Bull Racing,0 days 01:00:37.344000,2025-06-01 13:04:41.542,1,2.0,False,,False,True
2,0 days 01:03:17.964000,VER,1,0 days 00:01:20.537000,3.0,1.0,NaT,NaT,0 days 00:00:23.816000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:01:57.427000,2025-06-01 13:06:01.625,1,2.0,False,,False,True
3,0 days 01:04:38.996000,VER,1,0 days 00:01:21.032000,4.0,1.0,NaT,NaT,0 days 00:00:24.299000,0 days 00:00:32.612000,...,False,Red Bull Racing,0 days 01:03:17.964000,2025-06-01 13:07:22.162,1,2.0,False,,False,True
4,0 days 01:05:59.960000,VER,1,0 days 00:01:20.964000,5.0,1.0,NaT,NaT,0 days 00:00:24.223000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:04:38.996000,2025-06-01 13:08:43.194,1,2.0,False,,False,True

In [6]:
# Load Drivers (Max and Lando)
ver,nor = slipsel.pick_athletes(laps,["VER","NOR"])

In [7]:
# Verstappen Data
ver.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:00:37.344000,VER,1,0 days 00:01:23.696000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.318000,...,False,Red Bull Racing,0 days 00:59:13.393000,2025-06-01 13:03:17.591,1,2.0,False,,False,False
1,0 days 01:01:57.427000,VER,1,0 days 00:01:20.083000,2.0,1.0,NaT,NaT,0 days 00:00:24.125000,0 days 00:00:32.278000,...,False,Red Bull Racing,0 days 01:00:37.344000,2025-06-01 13:04:41.542,1,2.0,False,,False,True
2,0 days 01:03:17.964000,VER,1,0 days 00:01:20.537000,3.0,1.0,NaT,NaT,0 days 00:00:23.816000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:01:57.427000,2025-06-01 13:06:01.625,1,2.0,False,,False,True
3,0 days 01:04:38.996000,VER,1,0 days 00:01:21.032000,4.0,1.0,NaT,NaT,0 days 00:00:24.299000,0 days 00:00:32.612000,...,False,Red Bull Racing,0 days 01:03:17.964000,2025-06-01 13:07:22.162,1,2.0,False,,False,True
4,0 days 01:05:59.960000,VER,1,0 days 00:01:20.964000,5.0,1.0,NaT,NaT,0 days 00:00:24.223000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:04:38.996000,2025-06-01 13:08:43.194,1,2.0,False,,False,True

In [8]:
# Norris Data
nor.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
609,0 days 01:00:38.306000,NOR,4,0 days 00:01:24.658000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.807000,...,True,McLaren,0 days 00:59:13.393000,2025-06-01 13:03:17.591,1,3.0,False,,False,False
610,0 days 01:01:59.210000,NOR,4,0 days 00:01:20.904000,2.0,1.0,NaT,NaT,0 days 00:00:24.426000,0 days 00:00:32.574000,...,True,McLaren,0 days 01:00:38.306000,2025-06-01 13:04:42.504,1,3.0,False,,False,True
611,0 days 01:03:19.900000,NOR,4,0 days 00:01:20.690000,3.0,1.0,NaT,NaT,0 days 00:00:23.920000,0 days 00:00:32.553000,...,True,McLaren,0 days 01:01:59.210000,2025-06-01 13:06:03.408,1,3.0,False,,False,True
612,0 days 01:04:40.700000,NOR,4,0 days 00:01:20.800000,4.0,1.0,NaT,NaT,0 days 00:00:24.072000,0 days 00:00:32.502000,...,True,McLaren,0 days 01:03:19.900000,2025-06-01 13:07:24.098,1,3.0,False,,False,True
613,0 days 01:06:01.344000,NOR,4,0 days 00:01:20.644000,5.0,1.0,NaT,NaT,0 days 00:00:23.983000,0 days 00:00:32.529000,...,True,McLaren,0 days 01:04:40.700000,2025-06-01 13:08:44.898,1,3.0,False,,False,True