# Tyre and Stint Analysis

In [10]:
#Imports
import sys
import importlib
sys.path.append("../..")
import Sliplib.slipload as sl
import Sliplib.selection as slipsel
import Sliplib.plotting as slpolt

importlib.reload(slpolt)
importlib.reload(slipsel)

In [4]:
# Select GP and Load Session
session = sl.load_gp(2025,"Spanish Grand Prix","Race")
session.load()

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

In [5]:
#Load Lap data and head them
lap_data = session.laps
lap_data.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:00:37.344000,VER,1,0 days 00:01:23.696000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.318000,...,False,Red Bull Racing,0 days 00:59:13.393000,2025-06-01 13:03:17.591,1,2.0,False,,False,False
1,0 days 01:01:57.427000,VER,1,0 days 00:01:20.083000,2.0,1.0,NaT,NaT,0 days 00:00:24.125000,0 days 00:00:32.278000,...,False,Red Bull Racing,0 days 01:00:37.344000,2025-06-01 13:04:41.542,1,2.0,False,,False,True
2,0 days 01:03:17.964000,VER,1,0 days 00:01:20.537000,3.0,1.0,NaT,NaT,0 days 00:00:23.816000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:01:57.427000,2025-06-01 13:06:01.625,1,2.0,False,,False,True
3,0 days 01:04:38.996000,VER,1,0 days 00:01:21.032000,4.0,1.0,NaT,NaT,0 days 00:00:24.299000,0 days 00:00:32.612000,...,False,Red Bull Racing,0 days 01:03:17.964000,2025-06-01 13:07:22.162,1,2.0,False,,False,True
4,0 days 01:05:59.960000,VER,1,0 days 00:01:20.964000,5.0,1.0,NaT,NaT,0 days 00:00:24.223000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:04:38.996000,2025-06-01 13:08:43.194,1,2.0,False,,False,True

In [13]:
# Select a Driver
ver = lap_data.pick_drivers("VER")
ver.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:00:37.344000,VER,1,0 days 00:01:23.696000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.318000,...,False,Red Bull Racing,0 days 00:59:13.393000,2025-06-01 13:03:17.591,1,2.0,False,,False,False
1,0 days 01:01:57.427000,VER,1,0 days 00:01:20.083000,2.0,1.0,NaT,NaT,0 days 00:00:24.125000,0 days 00:00:32.278000,...,False,Red Bull Racing,0 days 01:00:37.344000,2025-06-01 13:04:41.542,1,2.0,False,,False,True
2,0 days 01:03:17.964000,VER,1,0 days 00:01:20.537000,3.0,1.0,NaT,NaT,0 days 00:00:23.816000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:01:57.427000,2025-06-01 13:06:01.625,1,2.0,False,,False,True
3,0 days 01:04:38.996000,VER,1,0 days 00:01:21.032000,4.0,1.0,NaT,NaT,0 days 00:00:24.299000,0 days 00:00:32.612000,...,False,Red Bull Racing,0 days 01:03:17.964000,2025-06-01 13:07:22.162,1,2.0,False,,False,True
4,0 days 01:05:59.960000,VER,1,0 days 00:01:20.964000,5.0,1.0,NaT,NaT,0 days 00:00:24.223000,0 days 00:00:32.561000,...,False,Red Bull Racing,0 days 01:04:38.996000,2025-06-01 13:08:43.194,1,2.0,False,,False,True

In [14]:
# Get Tyre Data
ver_tyre_data = slipsel.pick_tyre_data(ver)
ver_tyre_data.head(5)

  Driver  LapNumber Compound  TyreLife  FreshTyre  Stint
0    VER        1.0     SOFT       4.0      False    1.0
1    VER        2.0     SOFT       5.0      False    1.0
2    VER        3.0     SOFT       6.0      False    1.0
3    VER        4.0     SOFT       7.0      False    1.0
4    VER        5.0     SOFT       8.0      False    1.0

In [15]:
ver_tyre_data.groupby("Stint").agg({
    "LapNumber": ["min", "max"],
    "Compound": "first",
    "FreshTyre": "first"
})

      LapNumber       Compound FreshTyre
            min   max    first     first
Stint
1.0         1.0  13.0     SOFT     False
2.0        14.0  29.0     SOFT      True
3.0        30.0  47.0   MEDIUM      True
4.0        48.0  55.0     SOFT     False
5.0        56.0  66.0     HARD      True